name: Build

on:
  pull_request:
    branches:
      - bane-main
    types: [opened, synchronize]
    paths-ignore:
      - 'scripts/**'
      - '**/*.md'
  push:
    # Build for the bane-main branch.
    branches:
      - bane-main
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build geth [default: latest bane-main; examples: v0.92.0, 0a4ff9d3e4a9ab432fd5812eb18c98e03b5a7432]'
        required: false
        default: ''
      push_image:
        description: 'Push images to DockerHub [default: false; examples: true, false]'
        required: false
        default: 'false'
      use_latest_tag:
        description: 'Use `latest` tag while pushing images to DockerHub (applied to Ubuntu image only) [default: false; examples: true, false]'
        required: false
        default: 'false'

jobs:
  build_cli:
    name: Build geth and services
    runs-on: ${{matrix.os.name}}
    strategy:
      matrix:
        os: [{ name: ubuntu-22.04, bin-name: linux }, { name: macos-12, bin-name: darwin }]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          # Allows to fetch all history for all branches and tags. Need this for proper versioning.
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Build Alltools
        run: make all

      - name: Prepare Geth and Alltools target binaries
        run: |
          mkdir ./build/standalone
          cp ./build/bin/geth ./build/standalone/geth-${{ matrix.os.bin-name }}-${{ matrix.arch }}
          mv ./build/bin/ ./build/alltools-${{ matrix.os.bin-name }}-${{ matrix.arch }}

      - name: Upload Geth artifact
        uses: actions/upload-artifact@v4
        with:
          name: geth-${{ matrix.os.bin-name }}-${{ matrix.arch }}
          path: ./build/standalone/geth-${{ matrix.os.bin-name }}-${{ matrix.arch }}
          if-no-files-found: error

      - name: Upload Alltools artifact
        uses: actions/upload-artifact@v4
        with:
          name: alltools-${{ matrix.os.bin-name }}-${{ matrix.arch }}
          path: ./build/alltools-${{ matrix.os.bin-name }}-${{ matrix.arch }}
          if-no-files-found: error

      - name: Attach binaries to the release as assets
        if: ${{ github.event_name == 'release' }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./build/standalone/geth-${{ matrix.os.bin-name }}-${{ matrix.arch }}
          gh release upload ${{ github.event.release.tag_name }} ./build/alltools-${{ matrix.os.bin-name }}-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_image:
    name: Build and push Docker image
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Build geth
        run: |
          make geth
          ./build/bin/geth --version

      - name: Set env
        id: setvars
        run: echo "version=$(./build/bin/geth -v | sed -e "s/^geth version //" -e "s/-stable-.*//")" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_image == 'true') }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set latest tag
        id: setlatest
        if: ${{ (github.event_name == 'release' && github.event.release.target_commitish == 'bane-main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.use_latest_tag == 'true') }}
        run: |
          echo "latest=,annashaleva/neox_nodes:latest" >> $GITHUB_OUTPUT
          echo "alltoolslatest=,annashaleva/neox_nodes/alltools:latest" >> $GITHUB_OUTPUT

      - name: Build and push Geth
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_image == 'true') }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            REPO=github.com/${{ github.repository }}
            VERSION=${{ steps.setvars.outputs.version }}
            COMMIT=${{ github.sha }}
          tags: annashaleva/neox_nodes:${{ steps.setvars.outputs.version }}${{ steps.setlatest.outputs.latest }}
          file: Dockerfile

      - name: Build and push Alltools
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_image == 'true') }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            REPO=github.com/${{ github.repository }}
            VERSION=${{ steps.setvars.outputs.version }}
            COMMIT=${{ github.sha }}
          tags: annashaleva/neox_nodes/alltools:${{ steps.setvars.outputs.version }}${{ steps.setlatest.outputs.alltoolslatest }}
          file: Dockerfile.alltools
